
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: botfortelegram
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"

volumes:
  pgdata: